# Generated by Django 4.1.2 on 2024-02-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_latitude_user_longitude_user_place_user_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pic"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("active", "active"), ("suspend", "suspend"), ("ban", "ban")],
                default="active",
                max_length=50,
                null=True,
            ),
        ),
    ]
