# Generated by Django 4.1.2 on 2024-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_map_details_km_distance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map_details",
            name="km_distance",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("250", "500 Meters"),
                    ("500", "1 Km"),
                    ("1000", "2 Km"),
                    ("1500", "3 Km"),
                    ("2000", "4 Km"),
                    ("2500", "5 Km"),
                ],
                default="500",
                null=True,
            ),
        ),
    ]
