# Generated by Django 4.1.2 on 2024-02-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_map_details_km_distance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="map_details",
            old_name="title",
            new_name="place_name",
        ),
    ]
